### ISSUE TITLE
erzeugtes Markup nicht valide

### ISSUE THREAD

**Issue by miikesh** [heimrichhannot/contao-speed-bundle#3]
Hallo,

nach Einbinden der Erweitung in contao 4.4.38 erzeugt das Template picture_lazyload.html5 nicht valides HTML.
Auszug aus dem app_dev.php Quellcode

 <div class="ce_image last block">

     <figure class="image_container">

         
         <div id="image-wrapper-1290627171" class="image-wrapper">
             <div class="image-aspect-ratio">
                 <noscript>
                     <img src="assets/images/f/testbild-d18a30e2.jpg" srcset="assets/images/f/testbild-d18a30e2.jpg 400w, assets/images/1/testbild-ff80777a.jpg 800w, assets/images/1/testbild-c6f56e1c.jpg 1200w, assets/images/5/testbild-a52e4b58.jpg 1600w, assets/images/d/testbild-7e500f9b.jpg 2000w" sizes="(max-width: 600px) 100vw, 50vw" alt="test 1" title="test 1" itemprop="image">
                 </noscript>
                 <img data-wrapper="#image-wrapper-1290627171" data-wrapper-style="#image-wrapper-1290627171:not(.loaded){max-width:400px;max-height:250px}#image-wrapper-1290627171:not(.loaded) .image-aspect-ratio{padding-bottom:62.50%}" class="tns-lazy-image image lazy-img" data-lazy="http://m11.heise-homepage.de/assets/images/f/testbild-d18a30e2.jpg" data-src="http://m11.heise-homepage.de/assets/images/f/testbild-d18a30e2.jpg" data-srcset="http://m11.heise-homepage.de/assets/images/f/testbild-d18a30e2.jpg 400w, assets/images/1/testbild-ff80777a.jpg 800w, assets/images/1/testbild-c6f56e1c.jpg 1200w, assets/images/5/testbild-a52e4b58.jpg 1600w, assets/images/d/testbild-7e500f9b.jpg 2000w" sizes="(max-width: 600px) 100vw, 50vw"alt="test 1" title="test 1"itemprop="image">
             </div>
         </div>
         <script>
             window.respimage && window.respimage({
                 elements: [document.images[document.images.length - 1]]
             });
             </script>

         
     </figure>
 </div>
 

Habe ich etwas falsch gemacht beim Verwenden der Erweiterung oder woran kann das liegen?

[https://community.contao.org/de/showthread.php?74276-Bildgr%C3%B6%C3%9Fen-Fehler-im-Markup](url)

[http://m11.heise-homepage.de/](url)

Viele Grüße,
conter

**Comment by fatcrobat** [comment]
Die fehlenden Leerzeichen zwischen alt und itemprop haben wir in Version 1.8.1 behoben. Das Markup ist nur invalide, weil der W3C Validator vor dem Test kein Javascript ausführt.

Diesbezüglich gibt es vom Author des JS-Plugins `verlok/lazyload` einen Hinweis:

> We do not recommend to use a placeholder image (like a transparent pixel GIF) in your HTML. 
> 
> * For **best perceived performance, leave the `src` and `srcset` attributes blank**. Doing so, the image will be shown as soon as LazyLoad starts loading the image. See [this video](https://youtu.be/2E3ociaFJS0) or [this pen](https://> codepen.io/verlok/pen/bKYggE?editors=0110) to test the difference (remember to disable the cache and to set a slower connection speed if you have a very fast one).
> * If you put anything in the src (like a transparent GIF), then LazyLoad starts loading the image but it won't be shown by browsers until the new image is loaded, leading to a **worse perceived performance**.
>
> It's safe not to put any value in the `src` nor `srcset` attributes, even if your HTML won't validate by a static code analyzer. The reason is that once JavaScript is executed, those values will be set by LazyLoad. For SEO, if the  client is a crawler like Googlebot, it will be detected by LazyLoad which will fix the HTML.

Der W3C Validator sollte in der heutigen Zeit Javascript unterstützen, bzw. die `<noscript>` Tag Alternative verwenden.

Sollte es dich dennoch stören, so kannst du das Template `picture_lazyload.html5` gern überschreiben und Platzhalter bei src und srcset einsetzen.

**Comment by miikesh** [comment]
Vielen Dank für die Info! 

Am 13. März 2019, um 08:51, fatcrobat <notifications@github.com> schrieb:

Die fehlenden Leerzeichen zwischen alt und itemprop haben wir in Version 1.8.1 behoben. Das Markup ist nur invalide, weil der W3C Validator vor dem Test kein Javascript ausführt.

Diesbezüglich gibt es vom Author des JS-Plugins verlok/lazyload einen Hinweis:

We do not recommend to use a placeholder image (like a transparent pixel GIF) in your HTML.

For best perceived performance, leave the src and srcset attributes blank. Doing so, the image will be shown as soon as LazyLoad starts loading the image. See this video or [this pen](https://> codepen.io/verlok/pen/bKYggE?editors=0110) to test the difference (remember to disable the cache and to set a slower connection speed if you have a very fast one).

If you put anything in the src (like a transparent GIF), then LazyLoad starts loading the image but it won't be shown by browsers until the new image is loaded, leading to a worse perceived performance.


It's safe not to put any value in the src nor srcset attributes, even if your HTML won't validate by a static code analyzer. The reason is that once JavaScript is executed, those values will be set by LazyLoad. For SEO, if the client is a crawler like Googlebot, it will be detected by LazyLoad which will fix the HTML.

Der W3C Validator sollte in der heutigen Zeit Javascript unterstützen, bzw. die <noscript> Tag Alternative verwenden.

Sollte es dich dennoch stören, so kannst du das Template picture_lazyload.html5 gern überschreiben und Platzhalter bei src und srcset einsetzen.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
