### ISSUE TITLE
Warum lädt mit der Erweiterung immer Google Charts?

### ISSUE THREAD

**Issue by marcel-mathias-nolte** [heimrichhannot/contao-speed-bundle#6]
Warum lädt mit der Erweiterung immer Google Charts?
Auch in anonymen Tab (ohne Anmeldung etc.)? 
Das ist ja quasi ohne DS-GVO-Zustimmung gar nicht ladbar ... Gibts da einen Schalter?

**Comment by koertho** [comment]
Dieses Bundle ist eigentlich gar nicht mehr nötig, da Contao Lazy-Loading nun out-of-the-box unterstützt. 

Ansonsten habe ich mir den Code mal angeschaut und keine Stelle gefunden, wo Google Charts geladen wird. 

Grundsätzlich bei Issues bitte immer Contao- und Bundle-Version mit angeben.

**Comment by marcel-mathias-nolte** [comment]
ok danke für den hinweis, das nicht mehr benötigt wird. und sorry habe mich vertan:

der filename-sanitizer require haste_plus, und das lädt google charts

**Comment by koertho** [comment]
Ah ok. Das kannst du im Layout unter Komponenten deaktivieren.
